# -*- coding: utf-8 -*-
"""Enrollment in Korean Language.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1og8zSEKi9nqUkxR4KbVflCSCaNAGJKuU
"""

import pandas as pd
import numpy as np
import plotly.express as px

lang_df = pd.read_csv('Language enrollment.csv')

lang_df.head(3)

lang_df.columns

np.sum(lang_df['GRAD_TOTAL'])

lang_years_df = lang_df.groupby('SRVY_YEAR', as_index = False).agg({'ALL_LEVEL_TOTAL': 'sum'}).rename(columns={'SRVY_YEAR':'Year', 'ALL_LEVEL_TOTAL': 'Enrollment in languages'})
lang_years_df

"""-6.7% increase 2009-2013

3.7% increase 2013-2016
"""

lang_everything = lang_df.groupby(['SRVY_YEAR', 'LANGUAGE'], as_index = False).agg({'ALL_LEVEL_TOTAL': 'sum'}).rename(columns={'SRVY_YEAR':'Year', 'ALL_LEVEL_TOTAL': 'Enrollment in languages'})
lang_2009= lang_everything[lang_everything['Year'] == 2009]
lang_2016= lang_everything[lang_everything['Year'] == 2016]

#All languages in 2009 with enrollment above 5000
lang_2009 = lang_2009[lang_2009['Enrollment in languages'] > 5000]
lang_2009 = lang_2009[['LANGUAGE', 'Enrollment in languages']]
lang_2009

#All languages in 2016 with enrollment above 5000
lang_2016 = lang_2016[lang_2016['Enrollment in languages'] > 5000]
lang_2016 = lang_2016[['LANGUAGE', 'Enrollment in languages']]
lang_2016

#Percent increase from 2009 to 2016 for languages with enrollment above 5000
compare_all = lang_2009.merge(lang_2016, on='LANGUAGE', how='inner').rename(columns={'Enrollment in languages_x': '2009', 'Enrollment in languages_y': '2016'})
compare_all['Percent increase'] = ((compare_all['2016'] - compare_all['2009'])/compare_all['2009']) * 100

compare_all.sort_values(by = ['Percent increase'], ascending=False, inplace=True)
compare_all.reset_index(inplace = True)
compare_all = compare_all[['LANGUAGE', '2009', '2016', 'Percent increase']]

compare_all

"""After Korean, ASL was the next fastest growing widely learned language from 2009 to 2016. ASL enrollment grew 37% within this time span."""

lang_df['LANGUAGE'].nunique()

fig = px.scatter(lang_years_df, x="Year", y="Enrollment in languages", title='College Student Enrollment in Language Courses')
fig.show()

lang_df[lang_df['LANGUAGE'] == 'KOREAN']['LANG_CODE'].unique()
#Korean LANG_CODE is 47.0

np.sum(lang_df['LANG_CODE'] == 47.0)
##check if total matches below cell

np.sum(lang_df['LANGUAGE'] == 'KOREAN')
##1192 entries of Korean

kor_df = lang_df[lang_df['LANG_CODE'] == 47.0]

kor_years_df = kor_df.groupby('SRVY_YEAR', as_index = False).agg({'ALL_LEVEL_TOTAL': 'sum'}).rename(columns={'SRVY_YEAR':'Year', 'ALL_LEVEL_TOTAL': 'Enrollment in Korean'})
kor_years_df = kor_years_df.merge(lang_years_df, on='Year', how='right')

kor_years_df['Enrollment in Korean'] = kor_years_df['Enrollment in Korean'].fillna(0)

kor_years_df['Korean percent'] = (kor_years_df['Enrollment in Korean']/kor_years_df['Enrollment in languages'])*100

kor_years_df

"""45% increase 2009-2013

23% increase 2013-2016

**Slight** discrepency in 2013: NPR reported in 2015 that the year 2013 had enrollment at 12,229 rather than 12,256. Not sure how...
"""

fig = px.scatter(kor_years_df, x="Year", y="Enrollment in Korean", title='College Student Enrollment in Korean Language')
fig.show()

fig = px.scatter(kor_years_df, x="Year", y="Korean percent", title='Percent of students studying a language enrolled in Korean')
fig.show()

kor_colleges_df = kor_df.groupby('SRVY_YEAR', as_index = False)['UNIV'].nunique().rename(columns={'SRVY_YEAR':'Year', 'UNIV': 'Number of colleges offering Korean'})
kor_colleges_df = kor_colleges_df.merge(lang_years_df, on='Year', how='right')[['Year', 'Number of colleges offering Korean']]
kor_colleges_df['Number of colleges offering Korean'] = kor_colleges_df['Number of colleges offering Korean'].fillna(0)

kor_colleges_df

fig = px.scatter(kor_colleges_df, x="Year", y="Number of colleges offering Korean", title='Number of colleges offering Korean Language')
fig.show()

lang_df[lang_df['LANGUAGE'] == 'CHINESE']['LANG_CODE'].unique()
##Chinese LANG_CODE is 43.0

chin_df = lang_df[lang_df['LANG_CODE'] == 43.0]
len(chin_df)
#7337 entries of Chinese

chin_years_df = chin_df.groupby('SRVY_YEAR', as_index = False).agg({'ALL_LEVEL_TOTAL': 'sum'}).rename(columns={'SRVY_YEAR':'Year', 'ALL_LEVEL_TOTAL': 'Enrollment in Chinese'})

chin_years_df

"""2% increase 2009-2013

-4.9% increase 2013-2016
"""

fig = px.scatter(chin_years_df, x="Year", y="Enrollment in Chinese", title='College Student Enrollment in Chinese Language')
fig.show()

chin_colleges_df = chin_df.groupby('SRVY_YEAR', as_index = False)['UNIV'].nunique().rename(columns={'SRVY_YEAR':'Year', 'UNIV': 'Number of colleges offering Chinese'})
chin_colleges_df

fig = px.scatter(chin_colleges_df, x="Year", y="Number of colleges offering Chinese", title='Number of colleges offering Chinese')
fig.show()

lang_df[lang_df['LANGUAGE'] == 'JAPANESE']['LANG_CODE'].unique()
##Japanese LANG_CODE is 42.0

jap_df = lang_df[lang_df['LANG_CODE'] == 42.0]
len(jap_df)
#7857 entries of Japanese

jap_years_df = jap_df.groupby('SRVY_YEAR', as_index = False).agg({'ALL_LEVEL_TOTAL': 'sum'}).rename(columns={'SRVY_YEAR':'Year', 'ALL_LEVEL_TOTAL': 'Enrollment in Japanese'})
jap_years_df

"""-7.7% increase 2009-2013

12.7% increase 2013-2016
"""

fig = px.scatter(jap_years_df, x="Year", y="Enrollment in Japanese", title='College Student Enrollment in Japanese Language')
fig.show()

jap_colleges_df = jap_df.groupby('SRVY_YEAR', as_index = False)['UNIV'].nunique().rename(columns={'SRVY_YEAR':'Year', 'UNIV': 'Number of colleges offering Japanese'})
jap_colleges_df

fig = px.scatter(jap_colleges_df, x="Year", y="Number of colleges offering Japanese", title='Number of colleges offering Japanese')
fig.show()